### PR TITLE
HZ+ now works on Gelbooru.com

### LINKED ISSUE #61: Hover functionality for gelbooru.com
Image hover does not work on http://gelbooru.com/

### PR DESCRIPTION
**Pull request by GrosPoulet**
This update closes #61 (an issue opened in 2016 :open_mouth:)

### CODE REVIEW

File: plugins/safebooru.js [hunk 1]
```diff
@@ -19,10 +19,10 @@ hoverZoomPlugins.push({
...
         hoverZoom.urlReplace(res,
             'img[src]',
-            /(.*)\/(?:thumbnails|samples)\/(.*)\/(?:thumbnail|sample)_(.*)\.jpg(.*)/,
-            '$1/images/$2/$3.png'
+            /(.*)\/(?:thumbnails|samples)\/(.*)\/(?:thumbnail|sample)_(.*)/,
+            '$1/images/$2/$3'
         );
 
-        callback($(res));
+        callback($(res), this.name);
```
Comment (extesy) [inline plugins/safebooru.js:26]: I'm just curious, what is this doing? The callback function `imgLinksPrepared` only takes one parameter.

Comment (GrosPoulet) [reply plugins/safebooru.js:26]: It's for debugging, so you know which plugin found the high resolution url (it is not always obvious).
I use a slightly different version of HZ+where this info is handled.

Comment (extesy) [reply plugins/safebooru.js:26]: I see, thank you.
